# Generated by Django 4.0.6 on 2022-08-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=2, max_digits=2)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.classe')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.ecole'),
        ),
    ]
