# Generated by Django 4.0.6 on 2022-08-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
